### ISSUE TITLE
TypeError: Cannot assign to read only property '0' of string '...'

### ISSUE THREAD

**Issue by ghost** [soajs/soajs#5]
This error happens when we define an array type in the schema and we call the service with only one param.

config.js
`"schema": {
        "/XYZ": {
            "_apiInfo":{
                "l": "XYZ services"
            },
            "type":{
                "source": ['query.type'],
                "validation": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 0
                }
            }
        }
    }`

Call:
`localhost:4030/?type=...`

**Comment by mikehajj** [comment]
Hello Ghost,
your problem is not related to SOAJS or its IMFV wrapper. your problem is related to the validation of the input. 
The IMFV is built on top of jsonschema, as mentioned in this link: http://www.soajs.org/#/documentation/core/imfv.

if you want to learn more about what goes in the validation schema and why this syntax and not that syntax, you need to read more about jsonschema validation.
Here is the link for that: http://json-schema.org/latest/json-schema-validation.html
